introduced script for run.sh in order to grant permitions for presta …
mgdkmp13/ebiz_project pull request #21
Opened 2024-11-28 21:14 UTC by IwsonHD

…volume,scrapper now scrapps mega panels as well, NOTE:images of individual sub_cats are yet to be scrapped and structure of json will need to be changed #10 #4

2024-11-28 21:20 UTC, kacperwitczak commented
@IwsonHD 
1. zmiany w katalogu prestashop są nie potrzebne, spowodują one tylko konflikty przy dociąganiu innych branch'y, wycofaj te zmiany
2. sprawdziłem wymagania, i w katalogu projektu ma być tylko 5 folderów 
![image](https://github.com/user-attachments/assets/21a81db4-a9a8-42cc-9693-0139b5272660)
przenieś proszę dockercompose, dbinit, dumpdb run.sh do jednego folderu zgodnie z wymaganiami projektowymi

2024-11-28 21:21 UTC, kacperwitczak requested changes
@IwsonHD 
1. zmiany w katalogu prestashop są nie potrzebne, spowodują one tylko konflikty przy dociąganiu innych branch'y, wycofaj te zmiany
2. sprawdziłem wymagania, i w katalogu projektu ma być tylko 5 folderów 
![image](https://github.com/user-attachments/assets/21a81db4-a9a8-42cc-9693-0139b5272660)
przenieś proszę dockercompose, dbinit, dumpdb run.sh do jednego folderu zgodnie z wymaganiami projektowymi
dodatkowo rezultaty scrapowania powinny byc w osobnym folderze, tak jak jest to opisane w wymaganiach

2024-11-29 19:28 UTC, kacperwitczak approved these changes
lgtm!

2024-11-29 19:31 UTC, abialek677 approved these changes

2024-11-29 19:32 UTC, merged